import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-notion/src/styles.css";
import "prismjs/themes/prism-tomorrow.css";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import Link from "next/link";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} antialiased  flex flex-col min-h-screen`}
      >
        <header className="container mx-auto px-4 py-8 relative w-full text-start border-b-gray-200 border-b-[1px]">
          <Link href="/" className="text-2xl lg:text-3xl font-bold w-full">
            WT Shek
          </Link>
        </header>
        {children}
        <footer className="container py-4 px-4 mx-auto border-t mt-auto">
          <LanguageSwitcher />
          <div className="mt-4">
            Wing Tung Shek © {new Date().getFullYear()}
          </div>
        </footer>
      </body>
    </html>
  );
}
